
/****************************************************************************
  Generated by Enum.tt - don't make any changes in this file
****************************************************************************/

module RoadWatch.Models {

	 export type IRole = "SystemAdministrator" | "Anonymous";
	 export type IRoadConditionTypes = "Roadworks" | "VehicleCollision" | "Closure" | "Flooding" | "Harzard" | "SpecialEvent";
	 export type IFloodingTypes = "Impassable" | "Dangerous" | "Passable";
	 export type ICollisionTypes = "SingleVehicle" | "MultipleVehicles";
	 export type IHazardTypes = "RoadDamage" | "AnimalCrossing" | "PoorTraction" | "DebrisCover" | "BushFires" | "HeavyFog" | "HeavySmokeCover";
	 export type IConditionEffectTypes = "AllLanesAffected" | "AllDirections" | "DelaysExpected" | "ReducedSpeedLimit" | "ProceedWithCaution" | "NoDelaysExpected" | "ChangedTrafficConditions" | "RestrictedToFourWheelDrives" | "RestrictedToHighClearanceVehicles" | "TrafficControlOnScene";


	 export const Role = {
		 SystemAdministrator: "SystemAdministrator" as IRole,
		 Anonymous: "Anonymous" as IRole,
	 }
	 export const RoadConditionTypes = {
		 Roadworks: "Roadworks" as IRoadConditionTypes,
		 VehicleCollision: "VehicleCollision" as IRoadConditionTypes,
		 Closure: "Closure" as IRoadConditionTypes,
		 Flooding: "Flooding" as IRoadConditionTypes,
		 Harzard: "Harzard" as IRoadConditionTypes,
		 SpecialEvent: "SpecialEvent" as IRoadConditionTypes,
	 }
	 export const FloodingTypes = {
		 Impassable: "Impassable" as IFloodingTypes,
		 Dangerous: "Dangerous" as IFloodingTypes,
		 Passable: "Passable" as IFloodingTypes,
	 }
	 export const CollisionTypes = {
		 SingleVehicle: "SingleVehicle" as ICollisionTypes,
		 MultipleVehicles: "MultipleVehicles" as ICollisionTypes,
	 }
	 export const HazardTypes = {
		 RoadDamage: "RoadDamage" as IHazardTypes,
		 AnimalCrossing: "AnimalCrossing" as IHazardTypes,
		 PoorTraction: "PoorTraction" as IHazardTypes,
		 DebrisCover: "DebrisCover" as IHazardTypes,
		 BushFires: "BushFires" as IHazardTypes,
		 HeavyFog: "HeavyFog" as IHazardTypes,
		 HeavySmokeCover: "HeavySmokeCover" as IHazardTypes,
	 }
	 export const ConditionEffectTypes = {
		 AllLanesAffected: "AllLanesAffected" as IConditionEffectTypes,
		 AllDirections: "AllDirections" as IConditionEffectTypes,
		 DelaysExpected: "DelaysExpected" as IConditionEffectTypes,
		 ReducedSpeedLimit: "ReducedSpeedLimit" as IConditionEffectTypes,
		 ProceedWithCaution: "ProceedWithCaution" as IConditionEffectTypes,
		 NoDelaysExpected: "NoDelaysExpected" as IConditionEffectTypes,
		 ChangedTrafficConditions: "ChangedTrafficConditions" as IConditionEffectTypes,
		 RestrictedToFourWheelDrives: "RestrictedToFourWheelDrives" as IConditionEffectTypes,
		 RestrictedToHighClearanceVehicles: "RestrictedToHighClearanceVehicles" as IConditionEffectTypes,
		 TrafficControlOnScene: "TrafficControlOnScene" as IConditionEffectTypes,
	 }
	export const EnumLabelDictionary = {
		"RoleSystemAdministrator":"System Administrator",
		"RoleAnonymous":"Anonymous User",
		"RoadConditionTypesRoadworks":"Roadworks",
		"RoadConditionTypesVehicleCollision":"Vehicle Collision",
		"RoadConditionTypesClosure":"Road Closed",
		"RoadConditionTypesFlooding":"Flooding",
		"RoadConditionTypesHarzard":"Hazard",
		"RoadConditionTypesSpecialEvent":"Special Event",
		"FloodingTypesImpassable":"Area is impassable",
		"FloodingTypesDangerous":"Area is dangerous to cross",
		"FloodingTypesPassable":"Area is crossable with care",
		"CollisionTypesSingleVehicle":"Single vehicle invovled",
		"CollisionTypesMultipleVehicles":"Multiple vehicles involved",
		"HazardTypesRoadDamage":"Road damage",
		"HazardTypesAnimalCrossing":"Animal crossing",
		"HazardTypesPoorTraction":"Poor traction",
		"HazardTypesDebrisCover":"Debris covering road",
		"HazardTypesBushFires":"Bush fires",
		"HazardTypesHeavyFog":"Heavy fog",
		"HazardTypesHeavySmokeCover":"Heavy smoke cover",
		"ConditionEffectTypesAllLanesAffected":"All lanes affected",
		"ConditionEffectTypesAllDirections":"All directions affected",
		"ConditionEffectTypesDelaysExpected":"Delays expected",
		"ConditionEffectTypesReducedSpeedLimit":"Reduced speed limit",
		"ConditionEffectTypesProceedWithCaution":"Proceed with caution",
		"ConditionEffectTypesNoDelaysExpected":"No delays expected",
		"ConditionEffectTypesChangedTrafficConditions":"Changed traffic conditions",
		"ConditionEffectTypesRestrictedToFourWheelDrives":"Restricted to four wheel drive vehicles only",
		"ConditionEffectTypesRestrictedToHighClearanceVehicles":"Restricted to high clearance vehicles only",
		"ConditionEffectTypesTrafficControlOnScene":"Traffic control on scene",
		get: function(type, key) {
			return this[type + key];
		}
	}
}


