/****************************************************************************
  Generated by Enum.tt - don't make any changes in this file
****************************************************************************/
var RoadWatch;
(function (RoadWatch) {
    var Models;
    (function (Models) {
        Models.Role = {
            SystemAdministrator: "SystemAdministrator",
            Anonymous: "Anonymous",
        };
        Models.RoadConditionTypes = {
            Roadworks: "Roadworks",
            VehicleCollision: "VehicleCollision",
            Closure: "Closure",
            Flooding: "Flooding",
            Harzard: "Harzard",
            SpecialEvent: "SpecialEvent",
        };
        Models.FloodingTypes = {
            Impassable: "Impassable",
            Dangerous: "Dangerous",
            Passable: "Passable",
        };
        Models.CollisionTypes = {
            SingleVehicle: "SingleVehicle",
            MultipleVehicles: "MultipleVehicles",
        };
        Models.HazardTypes = {
            RoadDamage: "RoadDamage",
            AnimalCrossing: "AnimalCrossing",
            PoorTraction: "PoorTraction",
            DebrisCover: "DebrisCover",
            BushFires: "BushFires",
            HeavyFog: "HeavyFog",
            HeavySmokeCover: "HeavySmokeCover",
        };
        Models.ConditionEffectTypes = {
            AllLanesAffected: "AllLanesAffected",
            AllDirections: "AllDirections",
            DelaysExpected: "DelaysExpected",
            ReducedSpeedLimit: "ReducedSpeedLimit",
            ProceedWithCaution: "ProceedWithCaution",
            NoDelaysExpected: "NoDelaysExpected",
            ChangedTrafficConditions: "ChangedTrafficConditions",
            RestrictedToFourWheelDrives: "RestrictedToFourWheelDrives",
            RestrictedToHighClearanceVehicles: "RestrictedToHighClearanceVehicles",
            TrafficControlOnScene: "TrafficControlOnScene",
        };
        Models.EnumLabelDictionary = {
            "RoleSystemAdministrator": "System Administrator",
            "RoleAnonymous": "Anonymous User",
            "RoadConditionTypesRoadworks": "Roadworks",
            "RoadConditionTypesVehicleCollision": "Vehicle Collision",
            "RoadConditionTypesClosure": "Road Closed",
            "RoadConditionTypesFlooding": "Flooding",
            "RoadConditionTypesHarzard": "Hazard",
            "RoadConditionTypesSpecialEvent": "Special Event",
            "FloodingTypesImpassable": "Area is impassable",
            "FloodingTypesDangerous": "Area is dangerous to cross",
            "FloodingTypesPassable": "Area is crossable with care",
            "CollisionTypesSingleVehicle": "Single vehicle invovled",
            "CollisionTypesMultipleVehicles": "Multiple vehicles involved",
            "HazardTypesRoadDamage": "Road damage",
            "HazardTypesAnimalCrossing": "Animal crossing",
            "HazardTypesPoorTraction": "Poor traction",
            "HazardTypesDebrisCover": "Debris covering road",
            "HazardTypesBushFires": "Bush fires",
            "HazardTypesHeavyFog": "Heavy fog",
            "HazardTypesHeavySmokeCover": "Heavy smoke cover",
            "ConditionEffectTypesAllLanesAffected": "All lanes affected",
            "ConditionEffectTypesAllDirections": "All directions affected",
            "ConditionEffectTypesDelaysExpected": "Delays expected",
            "ConditionEffectTypesReducedSpeedLimit": "Reduced speed limit",
            "ConditionEffectTypesProceedWithCaution": "Proceed with caution",
            "ConditionEffectTypesNoDelaysExpected": "No delays expected",
            "ConditionEffectTypesChangedTrafficConditions": "Changed traffic conditions",
            "ConditionEffectTypesRestrictedToFourWheelDrives": "Restricted to four wheel drive vehicles only",
            "ConditionEffectTypesRestrictedToHighClearanceVehicles": "Restricted to high clearance vehicles only",
            "ConditionEffectTypesTrafficControlOnScene": "Traffic control on scene",
            get: function (type, key) {
                return this[type + key];
            }
        };
    })(Models = RoadWatch.Models || (RoadWatch.Models = {}));
})(RoadWatch || (RoadWatch = {}));
//# sourceMappingURL=Enums.js.map